In [2]:
'''
Data Science is the way to arrange the data which is required by machine in future.

Scientific Terminology:
Data science is a multidisciplinary blend of data interface algorithm development and technology, 
to solve any problem by complex analytics .
'''

'\nData Science is the way to arrange the data which is required by machine in future'

In [ ]:
'''
Libraries of data science
1 Numpy : Numerical Python
2 Pandas : Panel Data
3 nltk : Natural language toolkit(text processing)
4 webscraping : 
5 visualization library 
6 matplotlib
7 seaborn
8 tableau -(its paid)
9 sklearn
'''

In [ ]:
'''Algorithms :
KNN (k-nearest neighbour)'''

In [ ]:
'''
Numpy : History
came in 2005.
made by Jim Hugunin
Travis Oliphant modified it and launched the package

In numpy,we work on numbers
We can pass list,dictionary,set and tuple.

Data types:
Int 1  Signed: int8,int16,int32,int64
    2  Unsigned: 8bit,16bit,32bit,64bit
Float
     Float8,16,32,64
Complex
    complex64,complex128
    
i1 means 8bit
i2 means 16 bit etc.
               
               '''

In [ ]:
import numpy 
a=numpy.array()


In [6]:
import numpy as np
a=np.array([1,2,3,4,5,6],dtype =np.float32)
a

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [7]:
import numpy as np
a=np.array([1,2,3,4,5,6])
type(a)

numpy.ndarray

In [10]:
arr=np.arange(1,14,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13])

In [13]:
arr=np.arange(1,13,1)
mat=arr.reshape(4,3)
mat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
print(mat.T)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [15]:
mat[3]

array([10, 11, 12])

In [16]:
mat[3][1]

11

In [17]:
mat[1:3,1:3]

array([[5, 6],
       [8, 9]])

# 11 March

# NUMPY

In [1]:
import numpy as np

In [3]:
#obj=np.array(data,dtype=,copy)
dt=np.dtype(np.float16)
arr=np.array([1,2,3,4,5,6,7,8,9],dt)
arr

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float16)

In [4]:
arr=np.array({1:'Ram',2:'Mohan',3:'Sohan'})
arr

array({1: 'Ram', 2: 'Mohan', 3: 'Sohan'}, dtype=object)

In [5]:
arr=np.array(np.arange(1,12,1))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
a=np.arange(1,13,1)
b=a.reshape(4,3)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
c=np.arange(2,25,2).reshape(4,3)

In [17]:
c

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [18]:
np.add(b,c)

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27],
       [30, 33, 36]])

In [19]:
np.subtract(b,c)

array([[ -1,  -2,  -3],
       [ -4,  -5,  -6],
       [ -7,  -8,  -9],
       [-10, -11, -12]])

In [20]:
np.multiply(c,b)

array([[  2,   8,  18],
       [ 32,  50,  72],
       [ 98, 128, 162],
       [200, 242, 288]])

In [22]:
# For doing proper matrix multiplication

v=np.array([[1,2,3],[4,5,6],[7,8,9]])
x=np.array([[2,4,6],[8,10,12],[14,16,18]])
print(v)
print(x)
print(v.dot(x))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 60  72  84]
 [132 162 192]
 [204 252 300]]


Stacking

In [24]:
np.vstack([v,x])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [25]:
np.hstack([v,x])

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [28]:
print(np.zeros([4,3]))
print(np.ones([4,3]))
print(np.eye(3))
print(np.full([3,3],4))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [29]:
import numpy as np
dt=np.dtype('>i4')

In [30]:
print(dt)

>i4


In [31]:
dt

dtype('>i4')

In [32]:
student = np.dtype([('name','S20'),('age','i1'),('marks','f4')])

In [33]:
a = np.array([('Ramesh Kumar Singh Panwar',21,50),('Suresh',18,75)],dtype = student)
a

array([(b'Ramesh Kumar Singh P', 21, 50.), (b'Suresh', 18, 75.)],
      dtype=[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')])

# 12 March

In [1]:
#Boolean Array Indexing
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
b = a >=2
print(b)
print(a[b])
print(a[a > 2])

[[False  True]
 [ True  True]
 [ True  True]]
[2 3 4 5 6]
[3 4 5 6]


In [2]:
import numpy as np
x = np.array([[1,2],[3,4]])
print(x)
print(np.sum(x)) # Compute sum of all elements;
print(np.sum(x, axis=0)) # Compute sum of each column
print(np.sum(x, axis=1)) # Compute sum of each row

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


In [8]:
# BROADCASTING
import numpy as np
x = np.arange(1,13,1).reshape(4,3)
v = np.array([1,0,1])
#print(x.shape)
y = np.empty_like(x)
# Create an empty matrix with the

print(y)
#print(x)
#print(v)
for i in range(4):
    y[i, :] = x[i, :] + v
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [11]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
vv = np.tile(v, (4,1))
        # Stack 4 copies of v on top of 

print(vv)            # Prints "[[1,0,1]
                     #          [1,0,1]
                     #          [1,0,1]
                     #          [1,0,1]]"

y = x + vv     # Add x and vv elementwise
print(y)       # Prints "[[ 2 2 4
                #            5 5 7
                #            8 8 10
                #            11 11 13]]"


[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [9]:
import numpy as np
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print('Our array is : ' )
print(x)
print('\n')
rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]])
print(rows)
print(cols)
y = x[rows,cols]

print(' The corner elements of this array are:')
print(y)

Our array is : 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[[0 0]
 [3 3]]
[[0 2]
 [0 2]]
 The corner elements of this array are:
[[ 0  2]
 [ 9 11]]


In [13]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,11])

In [14]:
np.save('op',a)

In [15]:
x=np.load('op.npy')
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11])

# Pandas

In [ ]:
Panda is a panel data developed in 2009.
Three types of data structures:
1 Series (1D) : It is a heterogeneous data type
2 Data frame (2D)
3 Panel (3D) Panels are depricated in 3x and it can be removed when full version comes.

Rule in panda:
Whenever data is created,an index is created.

In [3]:
import pandas as pd
# ob=pd.Series(data,index,dtype,copy)

In [4]:
s=pd.Series([1,5,2,3,4])
s


0    1
1    5
2    2
3    3
4    4
dtype: int64

In [5]:
# Manual Indexing
s=pd.Series([1,2,3,4,5],index=[101,102,103,104,105])
s

101    1
102    2
103    3
104    4
105    5
dtype: int64

In [6]:
s=pd.Series([1,2,3],index=['a','b','c'])

In [7]:
s

a    1
b    2
c    3
dtype: int64

In [8]:
s[1]

2

In [9]:
s['a']

1

In [10]:
import numpy as np
s=pd.Series([1,2,3,4,5],dtype=np.float32)
s

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float32

In [11]:
s=pd.Series({1:'Ram',2:'Shyam',3:'Mohan','Sohan':32})
s

1          Ram
2        Shyam
3        Mohan
Sohan       32
dtype: object

In [13]:
s=pd.Series(5,index=[101,102,103,104,105])  #This is called Scalar
s

101    5
102    5
103    5
104    5
105    5
dtype: int64

In [14]:
s=pd.Series([1,2,3,4,5,6,7,8,9,10])
s

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [15]:
s[4:6]

4    5
5    6
dtype: int64

In [28]:
print(s[::2])

0    1
2    3
4    5
6    7
8    9
dtype: int64


In [21]:
df=pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [22]:
df

Empty DataFrame
Columns: []
Index: []

In [29]:
#df=pd.DataFrame(data,index,column,dtype,copy)
#df=pd.read_csv(data,names)

In [32]:
df=pd.DataFrame([1,2,3,4,5])
df

0
0  1
1  2
2  3
3  4
4  5

In [30]:
data = [['Alex',10],['Bob',12],['Clarke',13]]
df=pd.DataFrame(data)
print(df)

        0   1
0    Alex  10
1     Bob  12
2  Clarke  13


In [31]:
data = [['Alex',10],['Bob',12],['Clarke',13]]
df=pd.DataFrame(data)
print(df)
df1=pd.DataFrame(data,columns=['Name','Age'],index=[1001,1002,1003])
print(df1)

        0   1
0    Alex  10
1     Bob  12
2  Clarke  13
        Name  Age
1001    Alex   10
1002     Bob   12
1003  Clarke   13


In [34]:
df=pd.read_csv('practice.csv',names=['Name','Age','Salary'])
df
                # We created the file in notepad,and then save it  with .csv extension in notebook loc

Name  Age  Salary
0    Ram   23   45000
1   SHam   24   77655
2  Rohit   45  102300
3  Mohan   33   24500

In [42]:
#To create a tsv file.
#Write in a text editor,and save the file as .tsv
df=pd.read_csv('tsvfile.tsv',sep='\t',names=['Name','Age','Salary'])
df

Name  Age  Salary
0    Ram   33   20000
1   Sham   34  200200
2  Kamal   50  100000